apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"fla-springboot-backend"},"name":"fla-springboot-backend","namespace":"qzaydf-dev"},"spec":{"replicas":2,"selector":{"io.kompose.service":"fla-springboot-backend"},"strategy":{"resources":{}},"template":{"metadata":{"creationTimestamp":null,"labels":{"io.kompose.service":"fla-springboot-backend"}},"spec":{"containers":[{"image":"","name":"fla-springboot-backend","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"250m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}}}],"restartPolicy":"Always"}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["fla-springboot-backend"],"from":{"kind":"ImageStreamTag","name":"fla-springboot-backend:dev","namespace":"qzaydf-tools"}},"type":"ImageChange"}]},"status":{}}
  generation: 55
  labels:
    app: API
  name: fla-springboot-backend
  namespace: qzaydf-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    io.kompose.service: fla-springboot-backend
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: "6"
        memory: 2Gi
      requests:
        cpu: "6"
        memory: 1Gi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fla-springboot-backend
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: redis
            - name: NAVIGATION_BASE_URL
              value: "http://react-web-app-qzaydf-dev.pathfinder.gov.bc.ca/efiling"
          envFrom:
            - configMapRef:
                name: cso-webservcie-map
            - secretRef:
                name: splunk-hec
            - configMapRef:
                name: spring-profiles-active
          image: >-
            docker-registry.default.svc:5000/qzaydf-tools/fla-springboot-backend@sha256:1ea23b418ef5a1ec6d87892edcab380a7cbfb6cb133cb311857d640e4155b29e
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: fla-springboot-backend
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - fla-springboot-backend
        from:
          kind: ImageStreamTag
          name: "fla-springboot-backend:dev"
          namespace: qzaydf-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/qzaydf-tools/fla-springboot-backend@sha256:1ea23b418ef5a1ec6d87892edcab380a7cbfb6cb133cb311857d640e4155b29e
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2020-07-22T15:24:37Z"
      lastUpdateTime: "2020-07-22T15:24:37Z"
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: "2020-07-22T17:20:41Z"
      lastUpdateTime: "2020-07-22T17:20:44Z"
      message: >-
        replication controller "fla-springboot-backend-45" successfully rolled
        out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/qzaydf-tools/fla-springboot-backend@sha256:1ea23b418ef5a1ec6d87892edcab380a7cbfb6cb133cb311857d640e4155b29e
        type: ImageChange
    message: image change
  latestVersion: 45
  observedGeneration: 55
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
