version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    target-branch: "vulnerabilities"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend/efiling-frontend"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
  # npm dependencies - demo
  - package-ecosystem: "npm"
    directory: "/src/frontend/efiling-demo"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
