version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend"
    schedule:
      interval: "daily"
      time: "05:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend/efiling-frontend"
    schedule:
      interval: "daily"
      time: "05:00"
  # npm dependencies - demo
  - package-ecosystem: "npm"
    directory: "/src/frontend/efiling-demo"
    schedule:
      interval: "daily"
      time: "05:00"
