version: "2"
checks:
  similar-code:
    enabled: false
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      tests_patterns:
        - src/backend/**/test/**
  pmd:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
  # Backend File Specific Excludes
  - "src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/Keys.java"
  - "src/backend/efiling-worker/src/main/java/ca/bc/gov/open/jag/efilingworker/Keys.java"
  - "src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/fee/FeeService.java"
  - "src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/EfilingApiApplication.java"
  - "src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/mappers/SubmissionMapper.java"
  - "src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/service/SubmissionService.java"
  - "src/backend/efiling-backend-demo/src/main/java/ca/bc/gov/open/jag/efilingbackenddemo/EfilingBackendDemoApplication.java"
  - "src/backend/libs/efiling-lookup-client/src/main/java/ca/bc/gov/open/jag/efilinglookupclient/EfilingLookupService.java"
  - "src/backend/libs/efiling-status-client/src/main/java/ca/bc/gov/open/jag/efilingstatusclient/EfilingStatusService.java"
  - "src/backend/libs/efiling-submission-client/src/main/java/ca/bc/gov/open/jag/efilingsubmissionclient/EfilingSubmissionService.java"
  - "src/backend/**/test/**"

  # Frontend Pattern Excludes
  - "src/frontend/*/src/*.js"
  - "src/frontend/*/src/components/hoc/*.js"
  - "src/frontend/efiling-frontend/src/modules/confirmationPopupTestData.js"
  - "src/frontend/*/public/"
  - "src/frontend/*/.storybook/"
