version: "2"

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      tests_patterns:
        - src/backend/**/test/**
  pmd:
    enabled: true
  markdownlint:
    enabled: true

checks:
  similar-code:
    enabled: false

exclude_patterns:
  - "src/frontend/efiling-demo/src/*.js"
  - "src/frontend/efiling-frontend/src/*.js"
  - "src/frontend/efiling-demo/public/"
  - "src/frontend/efiling-frontend/public/"
  - "src/frontend/efiling-demo/.storybook/"
  - "src/frontend/efiling-frontend/.storybook/"
