package ca.bc.gov.open.jag.efilingreviewerapi.error;

public enum ErrorCode {

    CACHE_UNAVAILABLE,
    VIRUS_FOUND,
    DOCUMENT_VALIDATION,
    DOCUMENT_TYPE_MISMATCH,
    RESTRICTED_DOCUMENT,
    DOCUMENT_CONFIGURATION_NOT_FOUND,
    DOCUMENT_CONFIGURATION_MANAGEMENT

}
