REACT_APP_API_BASE_URL =  
REACT_APP_KEYCLOAK_URL = 
REACT_APP_KEYCLOAK_REALM = 
REACT_APP_KEYCLOAK_CLIENT_ID = 
REACT_APP_KEYCLOAK_CLIENT_SECRET = 
REACT_APP_API_KEYCLOAK_URL = 
REACT_APP_DEFAULT_IDENTITY_PROVIDER = 
REACT_APP_DEMO_CLIENT_ID = 