openapi: 3.0.0
info:
  version: 0.3.0
  title: jag-efiling-api
  description: Efiling api
servers:
  - url: 'http://localhost:8080'
tags:
  - name: submission
    description: Submission Api
paths:
  '/submission/generateUrl':
    post:
      summary: Generates a secure URL for e-filing submission
      operationId: GenerateUrl
      tags:
        - submission
      requestBody:
        description: requested parameters to generate a url
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateUrlRequest'
      responses:
        '200':
          description: File successfully received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateUrlResponse'
        '400':
          description: Account does not have role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EfilingError'
  '/submission/{id}/userDetail':
    get:
      summary: Get user detail for a given submission
      operationId: GetSubmissionUserDetail
      tags:
        - submission
      parameters:
        - name: id
          in: path
          description: A submission id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Config found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
        '404':
          description: Config not found
components:
  schemas:
    GenerateUrlRequest:
      description: details about the required transaction
      required:
        - userId
        - navigation
        - documentProperties
      properties:
        userId:
          type: string
          description: a unique identifier for the user
        documentProperties:
          $ref: '#/components/schemas/DocumentProperties'
        navigation:
          $ref: '#/components/schemas/Navigation'
    GenerateUrlResponse:
      description: A temporary url for uploading submission
      properties:
        expiryDate:
          type: integer
          format: int64
        efilingUrl:
          type: string
    UserDetail:
      type: object
      required:
        - csoAccountExists
      properties:
        csoAccountExists:
          type: boolean
          description: True if the user has a linked cso account
        hasEfilingRole:
          type: boolean
          description: True if the user has the efiling role
    DocumentProperties:
      type: object
      description: Submission Metadata used to describe the submission that will be e-filled
      required:
        - type
        - subType
        - documentAccess
      properties:
        type:
          type: string
          description: the submission type
        subType:
          type: string
          description: the submission sub type
        submissionAccess:
          $ref: '#/components/schemas/EndpointAccess'
          description: the endpoint to access submission(s)
    EndpointAccess:
      type: object
      description: Represent an http endpoint
      properties:
        url:
          type: string
        verb:
          type: string
          enum: [GET, POST]
        headers:
          type: object
          additionalProperties:
            type: string
    Navigation:
      required:
        - success
        - error
        - cancel
      properties:
        success:
          $ref: '#/components/schemas/Redirect'
        error:
          $ref: '#/components/schemas/Redirect'
        cancel:
          $ref: '#/components/schemas/Redirect'
    Redirect:
      required:
        - url
      properties:
        url:
          type: string
    EfilingError:
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
