package ca.bc.gov.open.jag.efilingapi.error;

public enum ErrorCode {
    INVALIDROLE,
    INVALIDUNIVERSAL,
    ACCOUNTEXCEPTION,
    DOCUMENT_TYPE_ERROR,
    PAYMENT_FAILURE,
    SUBMISSION_FAILURE,
    DOCUMENT_REQUIRED,
    DOCUMENT_STORAGE_FAILURE,
    FILE_TYPE_ERROR,
    CREATE_ACCOUNT_EXCEPTION,
    UPDATE_CLIENT_EXCEPTION,
    CACHE_ERROR,
    MISSING_UNIVERSAL_ID,
    MISSING_IDENTITY_PROVIDER,
    URL_GENERATION_FAILURE,
    INVALID_INITIAL_SUBMISSION_PAYLOAD,
    COURT_LOCATION_ERROR,
    MISSING_APPLICATION_CODE,
    FILING_PACKAGE_NOT_FOUND,
    DELETE_DOCUMENT_ERROR;
}
