package ca.bc.gov.open.jag.efilingapi.error;

public enum ErrorCode {
    ACCOUNTEXCEPTION,
    CACHE_ERROR,
    CREATE_ACCOUNT_EXCEPTION,
    COURT_LOCATION_ERROR,
    DELETE_DOCUMENT_ERROR,
    DOCUMENT_REQUIRED,
    DOCUMENT_STORAGE_FAILURE,
    DOCUMENT_TYPE_ERROR,
    FILE_TYPE_ERROR,
    FILING_PACKAGE_NOT_FOUND,
    INVALIDROLE,
    INVALIDUNIVERSAL,
    INVALID_INITIAL_SUBMISSION_PAYLOAD,
    MISSING_APPLICATION_CODE,
    MISSING_UNIVERSAL_ID,
    MISSING_REGISTRY_NOTICE,
    MISSING_IDENTITY_PROVIDER,
    PAYMENT_FAILURE,
    SUBMISSION_FAILURE,
    UPDATE_CLIENT_EXCEPTION,
    URL_GENERATION_FAILURE
}
