openapi: 3.0.0
info:
  version: 0.7.0
  title: jag-reviewer-api
  description: Efiling AI Reviewer api
servers:
  - url: "http://localhost:8080"
tags:
  - name: document
    description: Endpoints exposed to review document
security:
  - bearerAuth: []
paths:
  "/documents/extract":
    post:
      summary: Extract document form data
      operationId: ExtractDocumentFormData
      tags:
        - document
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/xDocumentType"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Document successfully received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentExtractResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    xTransactionId:
      name: X-Transaction-Id
      in: header
      required: true
      description: A unique Transaction Id generated by AI Reviewer clients
      schema:
        type: string
        format: uuid
    xDocumentType:
      name: X-Document-Type
      in: header
      description: A document type
      required: true
      schema:
        type: string
  schemas:
    DocumentExtractResponse:
      type: object
      description: Review upload response
