openapi: 3.0.0
info:
  version: 0.7.0
  title: jag-reviewer-api
  description: Efiling AI Reviewer api
servers:
  - url: "http://localhost:8080"
tags:
  - name: document
    description: Endpoints exposed to review document
paths:
  "/documents/extract":
    post:
      summary: Extract document form data
      operationId: ExtractDocumentFormData
      tags:
        - document
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/xDocumentType"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Document Form Data successfully extracted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentExtractResponse"
        "400":
          description: Request is not valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
components:
  parameters:
    xTransactionId:
      name: X-Transaction-Id
      in: header
      required: true
      description: A unique Transaction Id generated by AI Reviewer clients
      schema:
        type: string
        format: uuid
    xDocumentType:
      name: X-Document-Type
      in: header
      description: A document type
      required: true
      schema:
        type: string
  schemas:
    DocumentExtractResponse:
      type: object
      description: Review upload response
      required:
        - extract
        - document
      properties:
        extract:
          $ref: "#/components/schemas/Extract"
        document:
          $ref: "#/components/schemas/Document"
    Document:
      type: object
      required:
        - type
        - fileName
        - size
        - contentType
      properties:
        type:
          type: string
        fileName:
          type: string
        size:
          type: number
          format: integer
        contentType:
          type: string
    Extract:
      type: object
      required:
        - id
        - transactioniId
      properties:
        id:
          type: string
          format: uuid
        transactioniId:
          type: string
          format: uuid
    ApiError:
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string
