openapi: 3.0.0
info:
  version: 0.7.0
  title: jag-reviewer-api
  description: Efiling AI Reviewer api
servers:
  - url: "http://localhost:8080"
tags:
  - name: document
    description: Endpoints exposed to review document
  - name: admin
    description: Endpoints to admin efiling reviewer api
paths:
  "/documents/extract":
    post:
      summary: Extract document form data
      operationId: ExtractDocumentFormData
      tags:
        - document
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/xDocumentType"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Document Form Data successfully extracted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentExtractResponse"
        "400":
          description: Request is not valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  "/documents/event":
    post:
      summary: to inform api on a document event
      operationId: DocumentEvent
      tags:
        - document
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentEvent"
      responses:
        "204":
          description: Document Event acknoledged
  "/documentTypeConfigurations":
    get:
      summary: list all the document configuration
      operationId: GetDocumentConfigurations
      tags:
        - admin
      responses:
        "200":
          description: a list of document configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentTypeConfigurationList"
    post:
      summary: create a new document configuration
      operationId: createDocumentTypeConfiguration
      tags:
        - admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentTypeConfigurationRequest"
      responses:
        "201":
          description: document type configuration created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentTypeConfiguration"
components:
  parameters:
    xTransactionId:
      name: X-Transaction-Id
      in: header
      required: true
      description: A unique Transaction Id generated by AI Reviewer clients
      schema:
        type: string
        format: uuid
    xDocumentType:
      name: X-Document-Type
      in: header
      description: A document type
      required: true
      schema:
        type: string
  schemas:
    ApiError:
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string
    Document:
      type: object
      required:
        - type
        - fileName
        - size
        - contentType
      properties:
        type:
          type: string
        fileName:
          type: string
        size:
          type: number
          format: integer
        contentType:
          type: string
    DocumentExtractResponse:
      type: object
      description: Review upload response
      required:
        - extract
        - document
      properties:
        extract:
          $ref: "#/components/schemas/Extract"
        document:
          $ref: "#/components/schemas/Document"
    DocumentEvent:
      type: object
      properties:
        status:
          type: string
        documentId:
          type: number
          format: integer
    DocumentTypeConfigurationRequest:
      type: object
      properties:
        documentType:
          type: string
        documentTypeDescription:
          type: string
        projectId:
          type: integer
        documentConfig:
          type: object
    DocumentTypeConfiguration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        documentType:
          type: string
        documentTypeDescription:
          type: string
        projectId:
          type: integer
        documentConfig:
          type: object
    DocumentTypeConfigurationList:
      type: array
      items:
        $ref: "#/components/schemas/DocumentTypeConfiguration"
    Extract:
      required:
        - id
        - transactionId
      properties:
        id:
          type: string
          format: uuid
        transactionId:
          type: string
          format: uuid
