name: Build Efiling Admin Docker Image and Push to Openshift Image Registry

on:
  schedule:
    - cron: "0 0 * */3 *"
  push:
    branches: [artifactory]
    paths:
      - "src/frontend/efiling-demo/**"
      - ".github/workflows/dev-efiling-admin-build.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.EFILING_ARTIFACTORY_USERNAME }}
          password: ${{ secrets.EFILING_ARTIFACTORY_PASSWORD }}
      
      - name: Build Image
        run: |
          docker compose build efiling-demo
          docker tag jag-file-submission-efiling-demo artifacts.developer.gov.bc.ca/efc7-efiling-admin/efiling-admin:dev
      
      - name: Docker Push to Artifactory
        run: |
          docker push artifacts.developer.gov.bc.ca/efc7-efiling-repo/efiling-admin:dev