name: Build Efiling Admin Docker Image and Push to Openshift Image Registry

on:
  schedule:
    - cron: "0 0 * */3 *"
  push:
    branches: [master]
    paths:
      - "src/frontend/efiling-demo/**"
      - ".github/workflows/dev-efiling-admin-build-4.yml"
  workflow_dispatch:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }} -u ${{ secrets.OPENSHIFT4_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_SA_PASSWORD }}
      - name: Build the Docker image
        run: |          
          
          docker compose build efiling-demo
          
          docker tag jag-file-submission_efiling-demo ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE }}/efiling-admin:latest
          docker push ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE }}/efiling-admin:latest
