# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_1:
    name: Create and upload coverage artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify -P all --file src/backend/pom.xml
    - name: Upload java artifact result
      uses: actions/upload-artifact@v1
      with:
        name: coverage_report
        path: src/backend/coverage-report/target/site/jacoco-aggregate/jacoco.xml:jacoco
