# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    job_1:
      name: Create and upload Java coverage artifact
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B verify -P all --file src/backend/pom.xml
      - name: Upload java artifact result
        uses: actions/upload-artifact@v1
        with:
          name: java_coverage_report
          path: src/backend/coverage-report/target/site/jacoco-aggregate/jacoco.xml:jacoco
    
    job_2:
        name: Create and upload Javascript coverage artifact
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master	
          - uses: actions/setup-node@master
            with: 
              node-version: "12"
          - name: NPM Install
            run: npm install -g yarn
            working-directory: src/frontend/efiling-frontend
          - name:	Yarn Install
            run: yarn install	
            working-directory: src/frontend/efiling-frontend
          - name: Yarn Build	
            run: yarn build	
            working-directory: src/frontend/efiling-frontend
          - name: Yarn create Javascript coverage report
            
          - name: Upload javascript artifact result
            uses: actions/upload-artifact@v1
            with:
              name: javascript_coverage_report
              path: src/frontend/efiling-frontend/coverage/lcov.info:lcov
