name: pr-flow

on:
  push:
    branches: [ play/workflow ] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: docker-cache-{hash}
        restore-keys: |
          docker-cache-
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: ./src/backend
        build-args: | 
          SERVICE_NAME=efiling-api
          MVN_PROFILE=demo 
          STARTERS_V=v0.1.8 
        registry: docker.pkg.github.com
        repository: bcgov/jag-file-submission
        tags: efiling-api:latest
        # cache-from: type=registry,ref=efiling-api:latest
        # cache-to: type=inline
        push: true
        tag_with_ref: true
 