name: Update github pages

on:
  push:
    branches: [main]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "master"
          PULL_REQUEST_TITLE: "Sync github pages with new main changes."
          PULL_REQUEST_BODY: "please merge new code from {FROM_BRANCH} to update [live documentation](https://bcgov.github.io/jag-file-submission)"
